version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on:
      - php
    networks:
      - db-network

  php:
    container_name: php8.2_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    networks:
      - db-network

  mysql:
    image: mysql:5.7
    container_name: mysql5.7_container
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: # Contraseña vacía para root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # Permite acceso sin contraseña
      MYSQL_DATABASE: estudiantes-db
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - db-network

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin_container
  #   restart: always
  #   environment:
  #     PMA_HOST: mysql
  #     ALLOW_NO_PASSWORD: "true"
  #   ports:
  #     - "3308:80"
  #   depends_on:
  #     - mysql
  #   networks:
  #     - db-network

volumes:
  mysql-data:

networks:
  db-network:
    driver: bridge
